import { useRef, useEffect } from 'react'

const CODE128_MAP = {
  '0': 212222, '1': 222122, '2': 222221, '3': 121223, '4': 121322,
  '5': 131222, '6': 122213, '7': 122312, '8': 132212, '9': 221213,
  'A': 221312, 'B': 231212, 'C': 112232, 'D': 112322, 'E': 113222,
  'F': 113222, 'G': 211232, 'H': 211322, 'I': 212132, 'J': 212312,
  'K': 213122, 'L': 213212, 'M': 223112, 'N': 223121, 'O': 223211,
  'P': 231122, 'Q': 231212, 'R': 232112, 'S': 232211, 'T': 123122,
  'U': 123212, 'V': 124112, 'W': 124211, 'X': 131222, 'Y': 131222,
  'Z': 132122, '-': 141122, '.': 142112, ' ': 142211, '$': 232112,
  '/': 232211, '+': 233111, '%': 131222,
}

const START = 211412
const STOP = 2331112
const BAR_WIDTH = 2
const QUIET_ZONE = 10

export function generateBarcode(text) {
  const chars = text.toUpperCase().split('')
  const encoded = [START]
  for (const c of chars) {
    const code = CODE128_MAP[c]
    if (code) encoded.push(code)
  }
  encoded.push(STOP)
  return encoded
}

export function Barcode({ value, height = 60, className = '' }) {
  const canvasRef = useRef(null)

  useEffect(() => {
    if (!canvasRef.current || !value) return
    const canvas = canvasRef.current
    const ctx = canvas.getContext('2d')
    const bars = generateBarcode(value)
    const totalWidth = bars.reduce((s, b) => {
      const str = String(b)
      let w = 0
      for (const ch of str) w += parseInt(ch) * BAR_WIDTH
      return s + w
    }, 0)
    const fullWidth = totalWidth + QUIET_ZONE * 2
    canvas.width = fullWidth
    canvas.height = height
    ctx.fillStyle = 'white'
    ctx.fillRect(0, 0, fullWidth, height)
    ctx.fillStyle = 'black'
    let x = QUIET_ZONE
    for (const bar of bars) {
      const str = String(bar)
      for (const ch of str) {
        const w = parseInt(ch) * BAR_WIDTH
        ctx.fillRect(x, 0, w, height)
        x += w + BAR_WIDTH
      }
    }
  }, [value, height])

  if (!value) return null

  return (
    <canvas ref={canvasRef} className={className}
      style={{ maxWidth: '100%', height: 'auto' }} />
  )
}

export function renderTicketToCanvas(ticket) {
  const canvas = document.createElement('canvas')
  const ctx = canvas.getContext('2d')
  const w = 800, h = 500
  canvas.width = w
  canvas.height = h

  ctx.fillStyle = '#ffffff'
  ctx.fillRect(0, 0, w, h)

  ctx.fillStyle = '#6d28d9'
  ctx.fillRect(0, 0, w, 8)

  ctx.fillStyle = '#1f2937'
  ctx.font = 'bold 28px Arial, sans-serif'
  ctx.textAlign = 'center'
  ctx.fillText('MESOB - Appointment Ticket', w / 2, 50)

  ctx.fillStyle = '#6b7280'
  ctx.font = '14px Arial, sans-serif'
  ctx.fillText('Ethiopian Government Services Portal', w / 2, 72)

  ctx.strokeStyle = '#e5e7eb'
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(40, 88)
  ctx.lineTo(w - 40, 88)
  ctx.stroke()

  const fields = [
    ['Ticket Number', ticket.ticketNumber],
    ['Service', ticket.serviceTitle],
    ['Department', ticket.department || '-'],
    ['Date', ticket.appointmentDate ? new Date(ticket.appointmentDate).toLocaleDateString() : 'TBD'],
    ['Time', ticket.appointmentTime || 'TBD'],
    ['Fee', `${ticket.fee?.toLocaleString()} ETB`],
    ['Status', ticket.status],
  ]

  ctx.textAlign = 'left'
  let y = 120
  for (const [label, val] of fields) {
    ctx.fillStyle = '#6b7280'
    ctx.font = '13px Arial, sans-serif'
    ctx.fillText(label, 60, y)
    ctx.fillStyle = '#111827'
    ctx.font = 'bold 15px Arial, sans-serif'
    ctx.fillText(val, 240, y)
    y += 30
  }

  const bars = generateBarcode(ticket.ticketNumber)
  const totalWidth = bars.reduce((s, b) => {
    let w = 0
    for (const ch of String(b)) w += parseInt(ch) * 2
    return s + w
  }, 0)
  const bx = (w - totalWidth) / 2
  const by = y + 20
  ctx.fillStyle = '#000'
  let cx = bx
  for (const bar of bars) {
    for (const ch of String(bar)) {
      const bw = parseInt(ch) * 2
      ctx.fillRect(cx, by, bw, 60)
      cx += bw + 2
    }
  }

  ctx.fillStyle = '#374151'
  ctx.font = '12px Arial, sans-serif'
  ctx.textAlign = 'center'
  ctx.fillText(ticket.ticketNumber, w / 2, by + 85)

  ctx.fillStyle = '#9ca3af'
  ctx.font = '10px Arial, sans-serif'
  ctx.fillText('Generated by MESOB • ' + new Date().toLocaleString(), w / 2, h - 15)

  return canvas
}

export function downloadTicketImage(ticket) {
  const canvas = renderTicketToCanvas(ticket)
  const link = document.createElement('a')
  link.download = `ticket-${ticket.ticketNumber}.png`
  link.href = canvas.toDataURL('image/png')
  link.click()
}

export function downloadTicketPDF(ticket) {
  const printWindow = window.open('', '_blank')
  if (!printWindow) { alert('Please allow pop-ups to export tickets'); return }
  const canvas = renderTicketToCanvas(ticket)
  const imgData = canvas.toDataURL('image/png')
  printWindow.document.write(`
    <html><head><title>Ticket ${ticket.ticketNumber}</title>
    <style>
      body { margin: 0; display: flex; justify-content: center; align-items: center; min-height: 100vh; }
      img { max-width: 100%; height: auto; }
      @media print { body { margin: 0; } img { max-width: 100%; } }
    </style></head>
    <body><img src="${imgData}" onload="window.print(); window.close()" /></body></html>
  `)
  printWindow.document.close()
}
